In [25]:
import os
import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split # for training and testing
from sklearn.linear_model import LinearRegression # for using algorithm

In [26]:
df = pd.read_csv(r'G:\python\pandas\clean.csv')
df

,Unnamed: 0,bike_name,city,owner,brand,price,kms_driven,age,power
0,0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,1.0,TVS,35000.0,17654.0,3.0,110.0
1,1,Royal Enfield Classic 350cc,Delhi,1.0,Royal Enfield,119900.0,11000.0,4.0,350.0
2,2,Triumph Daytona 675R,Delhi,1.0,Triumph,600000.0,110.0,8.0,675.0
3,3,TVS Apache RTR 180cc,Bangalore,1.0,TVS,65000.0,16329.0,4.0,180.0
4,4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,1.0,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...,...
7309,9362,Hero Hunk Rear Disc 150cc,Delhi,1.0,Hero,25000.0,48587.0,8.0,150.0
7310,9369,Bajaj Avenger 220cc,Bangalore,1.0,Bajaj,35000.0,60000.0,9.0,220.0
7311,9370,Harley-Davidson Street 750 ABS,Jodhpur,1.0,Harley-Davidson,450000.0,3430.0,4.0,750.0
7312,9371,Bajaj Dominar 400 ABS,Hyderabad,1.0,Bajaj,139000.0,21300.0,4.0,400.0
7313,9372,Bajaj Avenger Street 220,Hyderabad,1.0,Bajaj,80000.0,7127.0,5.0,220.0

In [27]:
df.drop('Unnamed: 0',axis =1, inplace=True)

In [28]:
df

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,1.0,TVS,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,1.0,Royal Enfield,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,1.0,Triumph,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,1.0,TVS,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,1.0,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
7309,Hero Hunk Rear Disc 150cc,Delhi,1.0,Hero,25000.0,48587.0,8.0,150.0
7310,Bajaj Avenger 220cc,Bangalore,1.0,Bajaj,35000.0,60000.0,9.0,220.0
7311,Harley-Davidson Street 750 ABS,Jodhpur,1.0,Harley-Davidson,450000.0,3430.0,4.0,750.0
7312,Bajaj Dominar 400 ABS,Hyderabad,1.0,Bajaj,139000.0,21300.0,4.0,400.0
7313,Bajaj Avenger Street 220,Hyderabad,1.0,Bajaj,80000.0,7127.0,5.0,220.0

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.isnull().sum()

bike_name     0
city          0
owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [31]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [32]:
df =df.drop('bike_name' ,axis=1)

In [33]:
df =df.drop('city', axis=1)

In [34]:
df

      owner            brand     price  kms_driven  age  power
0       1.0              TVS   35000.0     17654.0  3.0  110.0
1       1.0    Royal Enfield  119900.0     11000.0  4.0  350.0
2       1.0          Triumph  600000.0       110.0  8.0  675.0
3       1.0              TVS   65000.0     16329.0  4.0  180.0
4       1.0           Yamaha   80000.0     10000.0  3.0  150.0
...     ...              ...       ...         ...  ...    ...
7309    1.0             Hero   25000.0     48587.0  8.0  150.0
7310    1.0            Bajaj   35000.0     60000.0  9.0  220.0
7311    1.0  Harley-Davidson  450000.0      3430.0  4.0  750.0
7312    1.0            Bajaj  139000.0     21300.0  4.0  400.0
7313    1.0            Bajaj   80000.0      7127.0  5.0  220.0

[7314 rows x 6 columns]

In [35]:
brand_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
              }
df['brand'] =df['brand'].map(brand_dict)
df

      owner  brand     price  kms_driven  age  power
0       1.0      1   35000.0     17654.0  3.0  110.0
1       1.0      2  119900.0     11000.0  4.0  350.0
2       1.0      3  600000.0       110.0  8.0  675.0
3       1.0      1   65000.0     16329.0  4.0  180.0
4       1.0      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7309    1.0      6   25000.0     48587.0  8.0  150.0
7310    1.0      7   35000.0     60000.0  9.0  220.0
7311    1.0     15  450000.0      3430.0  4.0  750.0
7312    1.0      7  139000.0     21300.0  4.0  400.0
7313    1.0      7   80000.0      7127.0  5.0  220.0

[7314 rows x 6 columns]

In [36]:
x =df.drop('price',axis=1)

In [37]:
y = df[['price']]

In [38]:
x_train, x_test, y_train, y_test =train_test_split(x , y,test_size=0.2,random_state=42) # here test size is the data we want to test on and random state is the data we want t otrain max

In [39]:
x_train

      owner  brand  kms_driven   age  power
5071    1.0      6      5500.0   3.0  100.0
565     1.0      1      2980.0   6.0  160.0
4500    1.0      1     68857.0  15.0  110.0
4030    1.0      8      7900.0   6.0  150.0
640     1.0      6     28329.0   6.0  110.0
...     ...    ...         ...   ...    ...
5191    1.0      6     19071.0   9.0  100.0
5226    1.0      2     19249.0   2.0  350.0
5390    1.0      7      5500.0   4.0  200.0
860     1.0      4     14836.0   8.0  150.0
7270    2.0      5     14000.0   4.0  250.0

[5851 rows x 5 columns]

In [40]:
x_test

      owner  brand  kms_driven  age  power
5832    1.0     10      3500.0  4.0  250.0
1562    1.0      2      3198.0  5.0  500.0
7181    1.0      7     62867.0  9.0  135.0
2825    1.0      7     25000.0  6.0  125.0
4890    1.0      7     15047.0  3.0  150.0
...     ...    ...         ...  ...    ...
57      1.0     12      2500.0  2.0  900.0
6192    1.0      7     17000.0  4.0  150.0
4411    1.0     15     16523.0  5.0  750.0
527     1.0     14      2881.0  7.0  250.0
3305    1.0      8     23833.0  4.0  150.0

[1463 rows x 5 columns]

In [41]:
y_train

         price
5071   50000.0
565    36000.0
4500   18000.0
4030   70000.0
640    32000.0
...        ...
5191   20000.0
5226  130000.0
5390  130000.0
860    40000.0
7270  120000.0

[5851 rows x 1 columns]

In [42]:
y_test

         price
5832  170000.0
1562  102850.0
7181   22000.0
2825   34200.0
4890   35500.0
...        ...
57    935000.0
6192   45000.0
4411  395000.0
527   140000.0
3305   54500.0

[1463 rows x 1 columns]

In [43]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5851, 5), (1463, 5), (5851, 1), (1463, 1))

In [44]:
from sklearn.svm import SVR,SVC

In [45]:
sv = SVR()
sv.fit(x_train,y_train)
import joblib
joblib.dump(sv,"sv_model.lb")

g:\project\bike price prediction\.venv\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

['sv_model.lb']

In [51]:
print("Score of training",sv.score(x_train,y_train))
print("Score of testing",sv.score(x_test,y_test))

Score of training -0.06121468224796467
Score of testing -0.06207297970664327

In [46]:
x_train

      owner  brand  kms_driven   age  power
5071    1.0      6      5500.0   3.0  100.0
565     1.0      1      2980.0   6.0  160.0
4500    1.0      1     68857.0  15.0  110.0
4030    1.0      8      7900.0   6.0  150.0
640     1.0      6     28329.0   6.0  110.0
...     ...    ...         ...   ...    ...
5191    1.0      6     19071.0   9.0  100.0
5226    1.0      2     19249.0   2.0  350.0
5390    1.0      7      5500.0   4.0  200.0
860     1.0      4     14836.0   8.0  150.0
7270    2.0      5     14000.0   4.0  250.0

[5851 rows x 5 columns]

In [47]:
y_train

         price
5071   50000.0
565    36000.0
4500   18000.0
4030   70000.0
640    32000.0
...        ...
5191   20000.0
5226  130000.0
5390  130000.0
860    40000.0
7270  120000.0

[5851 rows x 1 columns]

In [48]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(x_train,y_train)

g:\project\bike price prediction\.venv\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [49]:
import joblib
joblib.dump(rfr,"rfr1_model.lb")

['rfr1_model.lb']

In [ ]:
print("test score:",rfr.score(x_test,y_test))
print("training score:",rfr.score(x_train,y_train))

test score: 0.8776559875144081
training score: 0.9853700696050006

In [54]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor()
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [55]:
print("test score:",knr.score(x_test,y_test))
print("training score:",knr.score(x_train,y_train))

test score: 0.6322104076942667
training score: 0.7943042732023481

In [ ]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

In [23]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [24]:
pred = lr.predict(x_test)

In [25]:
pred

array([[151283.36369367],
       [216532.70392861],
       [ 32107.67693802],
       ...,
       [479661.58221205],
       [178109.46268514],
       [ 72659.54833235]], shape=(1463, 1))

In [26]:
y_test

         price
5832  170000.0
1562  102850.0
7181   22000.0
2825   34200.0
4890   35500.0
...        ...
57    935000.0
6192   45000.0
4411  395000.0
527   140000.0
3305   54500.0

[1463 rows x 1 columns]

In [27]:
# Accuracy
print("Test Score -->",lr.score(x_test,y_test))       
print("Training score-->",lr.score(x_train,y_train))

Test Score --> 0.7333487639992851
Training score--> 0.7155387850959116

In [28]:
from sklearn.datasets import load_breast_cancer
x ,y =load_breast_cancer(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC
z=SVC()
z.fit(x_train,y_train)
print("test score:",z.score(x_test,y_test))
print("training score:",z.score(x_train,y_train))

test score: 0.9473684210526315
training score: 0.9142857142857143

In [29]:
# without parameter
from sklearn.tree import DecisionTreeClassifier,DecisionTreeClassifier
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [30]:
print("test score:",dt.score(x_test,y_test))
print("training score:",dt.score(x_train,y_train))

test score: 1.0
training score: 1.0

In [31]:
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [32]:
# with parameter
dt = DecisionTreeClassifier(criterion='entropy',min_samples_leaf= 2, min_samples_split= 3,random_state=42)
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=3, random_state=42)

In [33]:
print("test score:",dt.score(x_test,y_test))
print("training score:",dt.score(x_train,y_train))

test score: 1.0
training score: 0.975

In [34]:
dt = DecisionTreeClassifier(criterion='entropy',min_samples_leaf= 3, min_samples_split= 2,random_state=4)
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=3, random_state=4)

In [35]:
print("test score:",dt.score(x_test,y_test))
print("training score:",dt.score(x_train,y_train))

test score: 1.0
training score: 0.9666666666666667

In [36]:
from sklearn.ensemble import RandomForestClassifier , RandomForestRegressor
from sklearn.datasets import load_diabetes
x,y = load_iris(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [37]:
print("test score:",rfc.score(x_test,y_test))
print("training score:",rfc.score(x_train,y_train))

test score: 1.0
training score: 1.0

In [38]:
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [39]:
rfc= RandomForestClassifier(criterion='entropy',min_samples_leaf= 3, min_samples_split= 2,random_state=4)
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', min_samples_leaf=3, random_state=4)

In [40]:
print("test score:",rfc.score(x_test,y_test))
print("training score:",rfc.score(x_train,y_train))

test score: 1.0
training score: 0.9583333333333334